fix(Error): add prunes bundle crane-operator.v1.6.0
Error: add prunes bundle crane-operator.v1.6.0
(kind-registry:5000/test-operator/crane-operator:v1.6.0) from package
crane-operator, channel release-v1.6: this may be due to incorrect
channel head (crane-operator.v1.6.1, skips/replaces [])